/*
 * fuzz the generator: random rule tables (every condition, every argument, alternatives for the same
 * number, errno rules, big sets) are turned into bytecode; the bytecode is run on random system call
 * data and compared with the independent oracle, and, for tables on a harmless system call, with what
 * the running kernel does with the same bytecode. VOW_FUZZ_SEED and VOW_FUZZ_N change the run.
 */
#include <errno.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <sys/wait.h>
#include <unistd.h>

#include "filter.h"
#include "oracle.h"
#include "t.h"

#define MAXR 16
#define MAXC 5
#define MAXSET 72

static uint64_t rng = 0x5eed;

static uint64_t
rnd(void)
{
	rng ^= rng << 13;
	rng ^= rng >> 7;
	rng ^= rng << 17;
	return rng;
}

static const uint64_t interesting[] = {
	0, 1, 2, 3, 4, 5, 7, 8, 15, 16, 17, 0x40, 0x41, 0x7f, 0x80, 0xff, 0x100, 0x1000, 0x8000, 0xffff,
	0x10000, 0x7fffffff, 0x80000000ull, 0xfffffffeull, 0xffffffffull, 0x100000000ull,
	0x100000001ull, 0xffffffff00000000ull, ~0ull, 0xdeadbeef00000001ull
};

static uint64_t
pick(void)
{
	if (rnd() % 4 == 0)
		return rnd();
	return interesting[rnd() % (sizeof interesting / sizeof *interesting)];
}

struct ft {
	struct vow_rule r[MAXR];
	struct vow_cond c[MAXR * MAXC];
	uint32_t set[MAXR * MAXC][MAXSET];
	size_t nr, nc;
	uint64_t used[MAXR * MAXC * 2];
	size_t nused;
};

static void
use(struct ft *f, uint64_t v)
{
	if (f->nused < sizeof f->used / sizeof *f->used)
		f->used[f->nused++] = v;
}

/* all rules on the same number if onenr != 0 (for the kernel run) */
static void
gen(struct ft *f, uint32_t onenr, int big)
{
	static const uint32_t nrs[] = { 102, 104, 107, 7, 9, 300, 20 };
	size_t i, k;

	memset(f, 0, sizeof *f);
	f->nr = 1 + rnd() % MAXR;
	for (i = 0; i < f->nr; i++) {
		struct vow_rule *r = &f->r[i];

		r->nr = onenr ? onenr : nrs[rnd() % (sizeof nrs / sizeof *nrs)];
		if (rnd() % 8 == 0) {
			r->err = 1 + (uint32_t)(rnd() % 100);
			continue;
		}
		r->ncond = (uint8_t)(rnd() % (big ? MAXC + 1 : 4));
		if (r->ncond > MAXC)
			r->ncond = MAXC;
		r->cond = &f->c[f->nc];
		for (k = 0; k < r->ncond; k++) {
			struct vow_cond *c = &f->c[f->nc];
			size_t si = f->nc;
			unsigned s, ns;

			f->nc++;
			c->arg = (uint8_t)(rnd() % 6);
			c->kind = VK_LO32;
			switch (rnd() % 7) {
			case 0:
				c->op = VC_EQ;
				c->v = pick();
				use(f, c->v);
				break;
			case 1:
				c->op = VC_EQ;
				c->kind = VK_FULL64;
				c->v = pick();
				use(f, c->v);
				break;
			case 2:
				c->op = VC_IN;
				ns = 1 + (unsigned)(rnd() % (big ? MAXSET : 7));
				for (s = 0; s < ns; s++) {
					f->set[si][s] = (uint32_t)pick();
					use(f, f->set[si][s]);
				}
				c->nset = (uint8_t)ns;
				c->set = f->set[si];
				break;
			case 3:
				c->op = VC_ALLBITS;
				c->v = (uint32_t)pick();
				use(f, c->v);
				break;
			case 4:
				c->op = VC_NOTALLBITS;
				c->v = (uint32_t)pick();
				use(f, c->v);
				break;
			case 5:
				c->op = VC_ONLYBITS;
				c->v = (uint32_t)pick();
				use(f, c->v);
				break;
			default:
				c->op = VC_MASKEQ;
				c->m = (uint32_t)pick();
				c->v = (uint32_t)pick() & (rnd() % 4 ? c->m : ~0u);
				use(f, c->v);
				break;
			}
		}
	}
}

static uint64_t
arg_for(const struct ft *f)
{
	uint64_t v;

	switch (rnd() % 4) {
	case 0:
		v = f->nused ? f->used[rnd() % f->nused] : pick();
		break;
	case 1:
		v = pick();
		break;
	default:
		v = f->nused ? f->used[rnd() % f->nused] : rnd();
		/* near a value used in a condition: one bit off, or the same low word with junk above */
		if (rnd() % 2)
			v ^= 1ull << (rnd() % 64);
		else
			v = (v & 0xffffffffull) | (rnd() << 32);
		break;
	}
	return v;
}

static void
fill(const struct ft *f, struct sdata *d, uint32_t onenr)
{
	size_t i;

	memset(d, 0, sizeof *d);
	d->arch = VOW_AUDIT_ARCH_X86_64;
	d->nr = onenr ? onenr : (f->nr ? f->r[rnd() % f->nr].nr : 0);
	if (!onenr && rnd() % 6 == 0)
		d->nr = (uint32_t)rnd() % 400;
	if (!onenr && rnd() % 40 == 0)
		d->nr |= VOW_X32_BIT;
	for (i = 0; i < 6; i++)
		d->args[i] = arg_for(f);
}

static unsigned
envn(const char *name, unsigned def)
{
	const char *e = getenv(name);

	return e ? (unsigned)strtoul(e, NULL, 0) : def;
}

static void
seed(void)
{
	rng = envn("VOW_FUZZ_SEED", 0x5eed) * 0x9e3779b97f4a7c15ull + 1;
}

/* generated bytecode against the independent oracle, no kernel involved */
static void
t_fuzz_interpreter_vs_oracle(void)
{
	static struct vow_insn prog[4096];
	struct vow_ctx ctx = { VOW_SECCOMP_RET_ERRNO | 1001 };
	struct ft *f = malloc(sizeof *f);
	unsigned tables = envn("VOW_FUZZ_N", 4000), t, built = 0, toobig = 0;
	unsigned long cases = 0, allow = 0, deny = 0, errs = 0;

	CHECK(f != NULL);
	seed();
	for (t = 0; t < tables; t++) {
		struct vow_table tb;
		size_t n;
		unsigned i;

		gen(f, 0, t % 5 == 0);
		tb.r = f->r;
		tb.n = f->nr;
		n = vow_build_tables(&tb, 1, &ctx, prog, 4096);
		if (n == 0) {
			/* it must say so, not emit something wrong */
			CHECK(errno == E2BIG);
			toobig++;
			continue;
		}
		built++;
		CHECK(bpf_validate(prog, n));
		for (i = 0; i < 300; i++) {
			struct sdata d;
			uint32_t g, o;

			fill(f, &d, 0);
			g = bpf_run(prog, n, &d);
			o = oracle_scan(&tb, 1, &ctx, &d);
			cases++;
			if (g == VOW_SECCOMP_RET_ALLOW)
				allow++;
			else if (g == ctx.deny)
				deny++;
			else
				errs++;
			if (g != o) {
				fprintf(stderr, "    seed %u table %u nr %u: bytecode 0x%x oracle 0x%x\n", envn("VOW_FUZZ_SEED", 0x5eed), t, d.nr, g, o);
				_exit(1);
			}
		}
	}
	printf("    %u tables built (%u too big, refused), %lu cases: %lu allow, %lu deny, %lu errno\n", built, toobig, cases, allow, deny, errs);
	CHECK(built > tables / 2 && allow > 1000 && deny > 1000 && errs > 100);
}

struct krep {
	volatile int checked, bad;
	char msg[2][160];
};

/* the same bytecode, judged by the kernel: rules on getuid, whose arguments are ignored by the call */
static void
t_fuzz_kernel(void)
{
	struct krep *rep = mmap(NULL, sizeof *rep, PROT_READ | PROT_WRITE, MAP_SHARED | MAP_ANONYMOUS, -1, 0);
	struct ft *f = malloc(sizeof *f);
	unsigned tables = envn("VOW_FUZZ_KN", 150), t, tested = 0;
	long total = 0;

	CHECK(rep != MAP_FAILED && f != NULL);
	seed();
	for (t = 0; t < tables; t++) {
		static const struct vow_rule keep[] = {
			{ VOW_NR_exit_group, 0, 0, NULL }, { VOW_NR_exit, 0, 0, NULL },
		};
		static struct vow_insn prog[4096];
		struct vow_ctx ctx = { VOW_SECCOMP_RET_ERRNO | 1001 };
		struct vow_table tb[2];
		size_t n;
		pid_t p;
		int st;

		gen(f, VOW_NR_getuid, 0);
		tb[0].r = keep;
		tb[0].n = 2;
		tb[1].r = f->r;
		tb[1].n = f->nr;
		n = vow_build_tables(tb, 2, &ctx, prog, 4096);
		if (n == 0)
			continue;
		rep->checked = rep->bad = 0;
		fflush(NULL);
		p = fork();
		CHECK(p >= 0);
		if (p == 0) {
			struct sdata d[200];
			uint32_t want[200];
			int i;

			alarm(20);
			for (i = 0; i < 200; i++) {
				fill(f, &d[i], VOW_NR_getuid);
				want[i] = oracle_scan(&tb[1], 1, &ctx, &d[i]);
				if (want[i] != bpf_run(prog, n, &d[i]))
					_exit(3);
			}
			if (vow_install(prog, n) != 0)
				_exit(4);
			for (i = 0; i < 200; i++) {
				long r;
				int e;

				errno = 0;
				r = syscall(VOW_NR_getuid, d[i].args[0], d[i].args[1], d[i].args[2], d[i].args[3],
				    d[i].args[4], d[i].args[5]);
				e = errno;
				rep->checked++;
				if (want[i] == VOW_SECCOMP_RET_ALLOW ? (r == -1 && e != 0) :
				    !(r == -1 && e == (int)(want[i] & 0xffff))) {
					if (rep->bad < 2)
						snprintf(rep->msg[rep->bad], sizeof rep->msg[0],
						    "want 0x%x, kernel r=%ld errno=%d, args %llx %llx %llx",
						    want[i], r, e, (unsigned long long)d[i].args[0],
						    (unsigned long long)d[i].args[1], (unsigned long long)d[i].args[2]);
					rep->bad++;
				}
			}
			_exit(rep->bad ? 1 : 0);
		}
		CHECK(waitpid(p, &st, 0) == p);
		if (!WIFEXITED(st) || WEXITSTATUS(st) != 0) {
			fprintf(stderr, "    seed %u table %u: child status 0x%x, %d disagreements\n",
			    envn("VOW_FUZZ_SEED", 0x5eed), t, st, rep->bad);
			if (rep->bad)
				fprintf(stderr, "    %s\n", rep->msg[0]);
			_exit(1);
		}
		tested++;
		total += rep->checked;
	}
	printf("    %u tables run through the kernel, %ld calls, no disagreement\n", tested, total);
	CHECK(tested > tables / 2);
}

/* a table that cannot fit in 255 instructions per block must be refused, never emitted wrong */
static void
t_fuzz_oversized_blocks(void)
{
	static struct vow_insn prog[4096];
	struct vow_ctx ctx = { VOW_SECCOMP_RET_ERRNO | 1001 };
	static uint32_t set[300];
	struct vow_cond c[6];
	struct vow_rule r;
	struct vow_table tb;
	unsigned k, ok = 0, refused = 0;

	for (k = 0; k < 300; k++)
		set[k] = k * 3;
	for (k = 1; k <= 300; k += 7) {
		size_t n, i;

		memset(c, 0, sizeof c);
		/* one rule with several big sets: the jump out of the block grows with k */
		for (i = 0; i < 6; i++) {
			c[i].op = VC_IN;
			c[i].arg = (uint8_t)i;
			c[i].kind = VK_LO32;
			c[i].nset = (uint8_t)(k > 255 ? 255 : k);
			c[i].set = set;
		}
		memset(&r, 0, sizeof r);
		r.nr = 102;
		r.ncond = 6;
		r.cond = c;
		tb.r = &r;
		tb.n = 1;
		errno = 0;
		n = vow_build_tables(&tb, 1, &ctx, prog, 4096);
		if (n == 0) {
			CHECK(errno == E2BIG);
			refused++;
			continue;
		}
		ok++;
		CHECK(bpf_validate(prog, n));
		{
			struct sdata d;
			size_t a;

			memset(&d, 0, sizeof d);
			d.arch = VOW_AUDIT_ARCH_X86_64;
			d.nr = 102;
			for (a = 0; a < 6; a++)
				d.args[a] = set[k > 1 ? k - 1 : 0];
			CHECK(bpf_run(prog, n, &d) == oracle_scan(&tb, 1, &ctx, &d));
			d.args[3] = 1;	/* not in the set */
			CHECK(bpf_run(prog, n, &d) == oracle_scan(&tb, 1, &ctx, &d));
		}
	}
	printf("    %u oversized rules built correctly, %u refused with E2BIG\n", ok, refused);
	CHECK(ok > 0 && refused > 0);
}

static const struct test tests[] = {
	{ "fuzz: bytecode against the oracle", t_fuzz_interpreter_vs_oracle, 0 },
	{ "fuzz: bytecode against the kernel", t_fuzz_kernel, 0 },
	{ "fuzz: oversized blocks are refused", t_fuzz_oversized_blocks, 0 },
};

int
main(void)
{
	(void)oracle;	/* the header also has the oracle of the promises; only the table scan is used here */
	return t_main(tests, (int)(sizeof tests / sizeof *tests), 3);
}
