#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# regenerate sysnames.h from the linux headers of this machine (x86-64 numbers). the output is checked in so the
# build does not depend on which headers a machine has; rerun it when a newer kernel adds syscalls.
set -eu
in=${1:-/usr/include/asm/unistd_64.h}
{
	echo "/* SPDX-License-Identifier: GPL-3.0-only */"
	echo "/* generated by gen-sysnames.sh from $(basename "$in"): the x86-64 system call names, for the report of vow-run -v */"
	grep '^#define __NR_[a-z0-9_]*[[:space:]]*[0-9]*$' "$in" |
	    awk '{ n = $2; sub(/^__NR_/, "", n); print $3 "\t" n }' | sort -n |
	    awk -F'\t' '{ printf "\t{ %s, \"%s\" },\n", $1, $2 }'
} > "$(dirname "$0")/sysnames.h"
